#!/usr/bin/python
# -*- coding: utf-8 -*-

import sqlite3 as lite
import sys

con = None

try:

	con = lite.connect('hungry.db')

	cur = con.cursor()    

	cur.execute("CREATE TABLE Sitios(Id INTEGER PRIMARY KEY AUTOINCREMENT, Texto TEXT)")
	cur.execute("CREATE TABLE Frases(Id INTEGER PRIMARY KEY AUTOINCREMENT, Texto TEXT)")
	sitios = ['vegana', 'japo metro', 'coordenadas', 'mesa redonda', 'caro', 'Monster', 'Ribs', 'creperia', 'woogabu','chino']
	count = 0
	for sitio in sitios:
		cur.execute("INSERT INTO Sitios VALUES("+str(count)+",'"+str(sitio)+"')")
		count += 1
	con.commit()

	frases = []
	frases.append('Si el rey se tira un pedo.. ¿Es un gas noble?')
	frases.append('Quizá no nieve, pero para ti van a haber 20 cm esta noche si o si.')
	frases.append('El ateísmo es una religión en el mismo sentido en que NO coleccionar sellos es un hobby.')
	frases.append('Este tipo es como el último metro. ¿Cómo el último metro?. Si, vamos, que viene con mucho retraso.')
	frases.append('El que mucho abarca poco aprieta. Moraleja: No te cases con una gorda.')
	frases.append('¿Por qué si una mujer se tira un puñado de hombres es una puta y si un hombre hace lo mismo es homosexual?')
	frases.append('Las bajas temperaturas obligan a los españoles a abrazar a sus esposas. Ha habido abrazos de más de diez minutos con susurros al oido.')
	frases.append('En Corea del Norte no les debe ir tan mal, a todos los que les he preguntado ¿Qué tal? Me han dicho: "No me puedo quejar".')
	frases.append('Perdone caballero, ¿Ha visto usted a Mistetas? No señora, pero deberia usted cambiarle el nombre a su perro porque se presta a confusion.')
	frases.append('Qué puta mierda cuando pone "abre fácil" y acabas usando una sierra radial.')
	frases.append('We serve vegetarians. Just tell us how you`d like them prepared. -A restaurant for carnivores-')
	frases.append('Cuando te cuenten un chiste, espera a que acaben de reir, para añadir: "Así murieron mis padres".')
	frases.append('Fitness feels great. Unfortunately, bacon feels better.')
	frases.append('- Doctor, ¿Cuánto me queda? - Diez -¿Diez qué? -Nueve...')
	frases.append('Egipto tendrá dictaduras cada cuatro años. La ONU respalda el derecho de un pueblo a cambiar de dictador.')
	frases.append('Todo el mundo tiene el derecho de ser estúpido, pero tu estás abusando de ese privilegio.')
	frases.append('Van Ramoncin y la Sinde en un barco que se esta hundiendo ¿Quién se salva? - La cultura')
	frases.append('Los amigos son como los árboles: Se caen cuando les golpeas repetidas veces con un hacha.')
	frases.append('Don`t be sexist! Bitches hate that!')
	frases.append('No hay palabras para decir todo lo que te quiero, así que olvídalo.')
	frases.append('Recently someone accused me of being insensitive, and I thought, how did this fat bitch get her wheel chair up the stairs to my house?')
	frases.append('La única debilidad de una tortuga es que no pueden darse la vuelta si estan de espaldas, asi que si pegas dos tortugas juntas... OMG!!')
	frases.append('Achievement: Refuse to do anything productive today Status: Mission Accomplished')
	frases.append('- Mama, Mama,en el cole me llaman Facebook. - ¿Y tu que les dices? - Me gusta')
	frases.append('-Ayer follé con una americana. -¿Y que tal tio? -Pufff, fatal tío, un caloorr, al final me la tuve que quitar.')
	frases.append('Admítelo. Hay un momento en tu vida en el que metes una pelota bajo tu camiseta y finges que estas embarazado.')
	frases.append('-Bombardeo sobre Libia.-Que informado sobre la actualidad estás.-Perdón, quise decir Lidia. Voy a ver un bukkake.')
	frases.append('Estaba claro que la relación con mi ex-novia no iba a funcionar. Yo soy géminis y ella una zorra hija de la gran puta.')
	frases.append('Señortias, cuando estais peleándoos. Consejo: Si dejais de agarrarla del pelo tendreis otra mano con la que golpearla. Solo andaba pensandolo. Seguid.')
	frases.append('Que triste es amar sin ser amado... Pero más triste es cagar sin haber almorzado.')
	frases.append('La nueva estrategia de nintendo contra la pirateria. La nintendo 3D de la nintendo 3DS no funciona si llevas un parche en el ojo.')
	frases.append('El problema cuando lees una cita en Internet es que nunca estás seguro de que sea auténtica.- Abraham Lincoln.')
	frases.append('¿Por qué tuenti tiene una opcion de dar a "Me gusta" a mi propio estado? ¡Pues claro que me gusta! Soy jodidamente gracioso. Y sexy.')
	frases.append('El Real Madrid me recuerda a Michael Jackson: promete espectáculo, vende las entradas y palma en casa.')
	frases.append('I can`t stop drinking about you.')
	frases.append('Iba a hacer algo hoy, pero todavia no he terminado el no hacer nada de ayer.')
	frases.append('Yo de pequeño corría que me las pelaba... y viceversa')
	frases.append('Si el aborto es asesinato, entonces las mamadas son canibalismo.')
	frases.append('El árbitro Muñiz Fernández recibe su insulto 900.000. "Me quedo con "comeojales" por su originalidad" reconoce.')
	frases.append('Hay veces que me siento solo... Otras veces me ayudan a sentarme.')
	frases.append('Vi una raja en los pantys de una universitaria y quise estudiar su carrera; Pero no me daba la media.')
	frases.append('-En este bar están las más guapas. -Si, las más guapas de Mordor. -¿Nos vamos? -Uhmm.. Nah. Aquí puedo pensar que no follo porque no quiero.')
	frases.append('And on the third day, God created the Remington bolt-action rifle, so that man could fight the dinosaurs... and the homosexuals.')
	frases.append('Te quiero sobre todas las cosas. Sobre la cama, por ejemplo.')
	frases.append('Cuando me pongo un pantalon apretado me siento .rar')
	frases.append('No puedo quedar hoy contigo. Tengo que sacar a pasear a mi unicornio.')
	frases.append('Ya tienes que ser muy hijoputa para que te mate un premio Nobel de la Paz... (Sobre la muerte de Bin Laden)')
	frases.append('El fútbol es lo más español del mundo. 22 tíos haciendo algo y el resto mirando.')
	frases.append('Barack Obama. El unico negro que ha tenido que convencer a todo el mundo que él cometio el crimen. (Sobre la muerte de Bin Laden)')
	frases.append('No hay limites de lo que puedes llegar a hacer cuando se supone que deberías estar haciendo otra cosa.')
	frases.append('Hemos comprado una mierda entre cinco. Somos copropietarios.')
	frases.append('Atheist fags, If there`s no god, how could evolution really be far as decide to use even go want to do look more like?')
	frases.append('No falla: es hacer la declaración de la renta, y a devolver.')
	frases.append('Y recordad, el próximo 22 de Mayo votad por el PP o el PSOE. Votad por la igualdad. ¡Hambre y miseria a partes iguales!')
	frases.append('When I grow up, I wanna be an unwashed hobo, standing on a corner, shouting racial slurs at his own genitals.')
	frases.append('Ayer subí corriendo las escaleras de casa y me encontré a mi novia follando con otro, lo cual es extrañísimo, porque soy tetrapléjico.')
	frases.append('Sentarte encima de tu pareja para que después, al acostarte con ella, parezca que lo haces con otra persona.')
	frases.append('Me han dado un teléfono inteligente y le he puesto un politono de Enrique Iglesias. Quiero ver cómo reacciona.')
	frases.append('Falete denunciará a los Desayunos de 24h de TVE por publicidad engañosa.')
	frases.append('Una mano en la cabeza (bien) Una mano en la cintura (fácil) Un movimiento sexi (ahí es donde me bloqueo)')
	frases.append('La única transparencia de un periódico es la que queda después de haber envuelto con él un bocata de sardinas.')
	frases.append('En Valladolid lo típico es masturbarse y después el lechazo.')
	frases.append('-Oye, ¿De donde viene Paco a estas horas? -De Francisco, a estas y a todas.')
	frases.append('- Cariño, si te haces rico ¿me pagas la lipo y las tetas?- ¿Tú pagarías por otro motor y ruedas nuevas al Renault Clio o comprarías un BMW?')
	frases.append('Justin`s "Never say never" has beat Michael Jackson`s "This is it" in movie sales. That`s just what he`d want. A young boy on top of him.')
	frases.append('My lesbian neighbors asked me what I wanted for my birthday. They gave me a Rolex. I think the misunderstood when I said "I wanna watch".')
	frases.append('Valor es llegar a casa manchado de carmin y darle un cachete en el culo a tu esposa y decirle: Vete preparandote que ahora te toca a ti.')
	frases.append('Acabo de poner mi movil en "modo avion" y lo he tirado por la ventana. El peor Transformer que he visto en mi vida, sin duda.')
	frases.append('Sabíamos que los virus los crean las empresas antivirus, ahora sabemos que los disturbios los crean los antidisturbios.')
	frases.append('En esta vida no me han regalado nada, todo he tenido que robarlo yo.')
	frases.append('Comer carne es un acto noble, ya que mandas a una vaquita al cielo, lejos de este mundo lleno de vegetarianos que se comen su comida.')
	frases.append('¿Cómo puede ser considerado un robo si la señal del wi-fi está traspasando toda mi puta casa?')
	frases.append('Desde que murió mi mujer, el sexo no ha vuelto a ser igual. Ahora apenas opone resistencia.')
	frases.append('Yo pago por el sexo porque mi madre dice que las cosas cuando cuestan dinero se valoran más.')
	frases.append('A mi novia le encanta jugar a los médicos conmigo. Llevo ya un año en lista de espera.')
	frases.append('¿Cuál es el colmo de un panadero? Que el alza del IPC afecte al precio del pan, y por ende, bajen las ventas.')
	frases.append('Te dije que estaba allí en 5 minutos, no hace falta que me llames cada media hora.')
	frases.append('Los celíacos no tragan, degluten.')
	frases.append('Hasta mi novia folla más que yo.')
	frases.append('-¿Cómo se escribe Bisbal? -Como suena. -¿Irritante, forzado y sobreactuado?')
	frases.append('Para terminar mi cumpleaños estaré en el Carrefour firmando libros. No sé hasta que hora, supongo que hasta que me pillen.')
	frases.append('Si quieres dejar tu trabajo, es mejor que te despidas de tu jefe con el corazón. Un dedo vale más que mil palabras.')
	frases.append('Si robar todo lo que te quepa en los bolsillos cuando vas a un bazar chino es delito, entonces ponedme las esposas, que también me las llevo')
	frases.append('A un esquizofrénico hay que saludarle como hacía Miliki: ¿Cómo están ustedes?')
	frases.append('Dale un pez a un hombre y comerá un dia. Dale una caña y pedirá una tapa.')
	frases.append('¿Está Coto Matamoros? Que se ponga.')
	frases.append('Trolling is a art.')
	frases.append('Tirarse un sonoro pedo en una reunión y decir "Les ruego dispensen mi pedantería".')
	frases.append('My phone auto-corrected "porn" to "poem" and now my girlfriend`s expectations for this evening are totally wrong.')
	frases.append('- Si me prestais atención... - Vale. Y lo haremos con un interés muy bajo.')
	frases.append('Tengo un amigo que es un sol. Sale y se pone.')
	frases.append('Todo lo que sé de la vida lo aprendí leyendo las etiquetas del champú. Por eso soy tan ignorante. Y tengo este pelazo.')
	frases.append('Ahora mismo acabas de darte cuenta que estás respirando. [Manual breathing mode = on]')
	frases.append('- Salgamos corriendo de este bar, sin que nos vea el camarero. + ¿Por qué? - Por la cuenta que nos trae.')
	frases.append('-Pareces un camionero tía. -Es que estoy ronca. -¿Y cuál es la excusa para el bigote?')
	frases.append('-¿Este pantalón me hace gorda? -No metas al pantalón en esto... él no tiene nada que ver.')
	frases.append('First world problems: I don`t have a girlfriend or wife, so I have to make my own sandwiches.')
	frases.append('-Un gintoni, por favor. -Le pongo pepino, caballero? -Desde el primer día que la vi, señorita. Lamento que se me note tanto.')
	frases.append('Este verano, el destino favorito de los españoles es el Nilo. "Nilo podemos pagar ahora, Nilo podemos pagar a plazos. Así que Nilo sueñes".')
	frases.append('En el pelotón de fusilamiento: -¿Un último deseo? +¡Que me dispare Fernando Torres!')
	frases.append('Con un 6 y un 4... No, espera... Con un 9 y un 2... No, tampoco... Con un 2 y un 8... JODER, ¿¡POR QUE ERES TAN FEO!?.')
	frases.append('My smartphone ran out of batteries and now I have to use a paper map like Christopher Fucking Columbus. First World Problems')
	frases.append('Agorafobia: no salgo de casa sin ella.')
	frases.append('Si no cometes pecados Jesus murió en vano.')
	frases.append('La única diferencia entre el sexo gratis y el sexo pagando es que el sexo gratis sale mucho más caro.')
	frases.append('Titanic al revés: Va de un submarinista llamado Jack, que sube a un barco a mediohacer, y se lía con una ricachona que acaba pasando de él.')
	frases.append('¿Por qué la "Paciencia" es una virtud? ¿Por qué no puede ser una virtud el "Date prisa de una puta vez"?')
	frases.append('Hoy tenía un hambre de perros. Pedí comida china. Asunto resuelto.')
	frases.append('Toda tía que escupe, esputa.')
	frases.append('Típica conversación en el coche con tu Chica: Ella: ¿Cariño qué nos está pasando? Tu: ¡Un Ferrari! ¡Que hijo puta míralo!')
	frases.append('Para más información sobre el cancer de pulmón, siga fumando.')
	frases.append('El pintxo de chuletón es la tapa reina del Tour de Francia.')
	frases.append('He ido a casa de unos vecinos que no conocía y me han dicho: "Siéntete como en tu casa". He ido al ordenador y he empezado a bajar porno.')
	frases.append('-Hermione, ¿Sabes como invocar a un millon de minimagos?. +¡Harry, no hay tal clase de...! -Fap, fap, fap, fap...')
	frases.append('El siguiente ingrediente que necesitaremos serán tres huevos, pero no les vamos a romper porque eso es aborto.')
	frases.append('El otro día me hice cuenta en Google+. Es gracioso como Google se hace el tonto y me pide que rellene mi información personal.')
	frases.append('Cada vez que me voy de vacaciones, mi novia acaba teniendo relaciones sexuales, así que esta vez, me la llevaré conmigo.')
	frases.append('-Me gusta cuando callas.-Porque estoy como ausente...-A ver, ¿qué parte no has entendido?')
	frases.append('Can you repeat the part of the stuff where you said all about the things?')
	frases.append('- ¿La mamá se come al bebé con su vagina y lo celebra con papá teniendo sexo? Estaba tan dormido que le leí el libro a mi hija al revés.')
	frases.append('Hay dos clases de personas: A los que les gusta la cerveza... ¡y el resto de vosotros pobres bastardos!')
	frases.append('-Si muriese mañana, ¿qué me dirías hoy? -Ve hacia la luz.')
	frases.append('Soy un Dios para las mujeres. Sólo acuden a mí cuando necesitan algo.')
	frases.append('Morir ahogado en la playa es paradójico: Es decir adiós entre olas.')
	frases.append('Molaria tener de 2º nombre como te concibieron:-¿Cómo te llamas? -Antonio Condón Roto,¿y tú? -Yo Cristina Alobestia Contraelsuelo, encantada.')
	frases.append('Creo que a esta camarera le gusto. Es la tercera vez que me dice que me guarde el cigarro para después.')
	frases.append('Un guardia civil me ha pillado 20 euros de hachís en la guantera. No contento, me pide los papeles. Al final voy a tener que liárselo y todo.')
	frases.append('-¿Conoces este juego? ¡Tírame del dedo! -Sí, ya lo conozco... Pero la lepra no es una broma, Juan. Sólo te quedan tres. Tú sabrás.')
	frases.append('-Policía: "¿Me da su permiso de conducir?" -"Conduzca, agente, conduzca."')
	frases.append('La religión es como el pene, está bien tener uno, y estar orgulloso de él, pero no está bien tratar de meterselo a la fuerza a los demás.')
	frases.append('-¿Y tú como duermes? +De lado. Con el culo hacia mi marido. -¿Y eso? +No sé. Me da por ahí.')
	frases.append('- Doctor, me lo recomendó para los ardores y ahora tengo ladillas. - ¡Le dije sal de frutas!')
	frases.append('Te conquistaría, preciosa, pero mis aldeanos no han recolectado la suficiente madera.')
	frases.append('-¿Qué quieres hacer? -¡¡¡¡Follar!!!! -Ahora no. -Joder... -¡Te he dicho que no! -¡Que te den! -Y dale...')
	frases.append('Errar es de humanos, herrar es de herreros, y E.rar es de geeks.')
	frases.append('Ha sido un negocio tener placer con usted.')
	frases.append('Ayer, aparcando, un policía me dijo que allí no se podía. Y sí, me costó meterlo, pero le demostré que SE PODíA. El tío tomó apuntes y todo...')
	frases.append('- Este dibujo nos le ha enviado Robert de 9 años. Es una puta mierda, Robert. Hay niños en china de tu edad que pueden hacer zapatos.')
	frases.append('-I like my women like I like my math: Pure and beautiful. + I rather like my women like I like my math: Easy and at a highschool level.')
	frases.append('¿Cómo localizarías a un vegetariano en una habitacion llena de gente? Tranquilo, te lo hará saber.')
	frases.append('Cada vez que alguien hace un chiste de disléxicos Dios gata a un matito.')
	frases.append('Qué susto. Pensé que me había dejado el iPhone sobre un banco del parque pero no, era mi sobrino.')
	frases.append('Odio todas esas películas tan poco realistas en las que aparecen mujeres siendo amigas.')
	frases.append('A la mierda mi Iphone, ¡quiero una pokedex!')
	frases.append('Mi vecino llamó a mi casa a las 2:30 am. Te lo puedes creer?! ¡2:30 am! Por suerte para él todavía estaba despierto tocando la batería.')
	frases.append('Estoy enamorado de mi cama. Estamos hechos el uno para el otro, pero a mi alarma no parece que le guste que estemos juntos. Puta celosa.')
	frases.append('- Oye, ¿y si ahora que parece dormido nos sacamos una foto con la polla en su boca?+ Joder, Luis, que estás en el funeral de tu abuelo...')
	frases.append('A los huracanes tendrían que ponerles nombres estilo "Megamurder 3000" y dejarse de mariconadas.')
	frases.append('Hoy te voy a hacer el amor como los Jedi: A la fuerza.')
	frases.append('Hoy te voy a hacer el amor como los Sith: Por el lado oscuro.')
	frases.append('Acabo de rociar a un mosquito con mi spray anti-mosquitos. Ahora nunca tendrá amigos.')
	frases.append('¿Sabes cuando te dicen que el sexo es como andar en bicicleta? Bueno, pues tampoco tengo bicicleta.')
	frases.append('"No estás practicando sexo prematrimonial si nunca te vas a casar." Creo que los curas pillaron rápido ese concepto.')
	frases.append('¿Se cuece como Aznar o se enriquece como Camps? #preguntaleamariano')
	frases.append('-¡Prometiste que no se lo dirias! +Y Hitler prometió no invadir Checoslovaquia... Bienvenido al mundo real!')
	frases.append('- Su operación ha salido perfectamente señora López.- ¿Cómo que señora?- ¿Qué?')
	frases.append('Me encanta el cine, sobre todo cuando apagan las luces y empiezo a robar bolsos.')
	frases.append('-Papá, ¿cuál ha sido la mayor decepción de tu vida? -No estoy seguro, hijo. ¿Ya mides más que tu madre?')
	frases.append('Mi novia me llamó pedófilo. Me extrañó mucho porque es una palabra realmente complicada para una niña de 6 años.')
	frases.append('Acabo de imprimir una cosa sin darle a "Vista previa de impresión", así, directamente.A veces a la vida hay que echarle un par de cojones.')
	frases.append('Para conseguir grandes resultados, trabaja siempre en algo importante, usándolo como forma de evitar hacer algo que sea aún más importante.')
	frases.append('Vegetarianos! ¡Dejad de comeros la comida de mi comida!')
	frases.append('Sabes que te estás haciendo viejo cuando tus amigas empiezan a tener hijos a proposito.')
	frases.append('- ¿Sabe si han pasado ya los suevos, vándalos y alanos?- Sí, hace una horda.')
	frases.append('-Eres una zorra. -¿Me estás llamando persona astuta y solapada? -No, no, te estoy llamando puta, pero he encontrado un vacío legal cojonudo.')
	frases.append('Iba en el coche cuando se puso a adelantarme una gorda en moto. Le grité "¡Vaca!". Ella me contestó "¡Imbécil!" y se estampó contra la vaca.')
	frases.append('Repetir una contraseña incorrecta, igual pero más despacio y tecleando fuerte, con un dedo. Como hablar inglés en castellano lento y gritado')
	frases.append('Soy un tipo que me mantengo fiel a mi mismo. O sea, lo de sexo con otras personas, poco.')
	frases.append('Todo lo que sube baja. Excepto la tapa del váter.')
	frases.append('Señor juez, si amar es un delito, me declaro culpable. -Cállese, que usted está aquí por conducir borracho.')
	frases.append('-Jesús...-Dime, Judas.-Es por lo de la cena esa...-Dime.-¿Invitas tú a todos?-Sí, claro.-¡Pues te van a clavar!-No creo... ¿De qué te ríes?')
	frases.append('Tengo el gatillo fácil. El jodío minino se va con la primera gata con que se cruza.')
	frases.append('Si ves Dexter de atras a adelante va sobre un Dr. Frankenstein sin emociones pero realmente exitoso.')
	frases.append('Esto del cyber sexo no es tan fácil como parece. Debería haber escogido un Starbucks con menos gente.')
	frases.append('Hoy en citas famosas: "No soy como la mayoría de las chicas" -La mayoría de las chicas.')
	frases.append('La primera paja es como comerse un kebab: rápido, sucio y barato, ¡pero muy rico! Y siempre deja manchas en la ropa.')
	frases.append('La cucaracha, la cucaracha ya... *Sale Pitbull* -¿No puede caminar?.. Vamos mamacita YEAH! ¡Daleee!.. 1..2..3... ¡CAMINA!.')
	frases.append('Desde que dejé de usar Colgate Sensitive tengo menos sensibilidad. Mira, un niño muerto. Como te iba diciendo...')
	frases.append('Bienvenidos a Internet, donde los hombres son hombres, las mujeres son hombres y las niñas son agentes de la guardia civil')
	frases.append('-¿Me puede decir un nombre para que me pueda dirigir a usted? -Aragorn, hijo de Arathorn, heredero de Isildur (Hablando Con Movistar)')
	frases.append('Caminando por la calle vi aun negro cargando un televisor. Pensé "se parece al mio", pero el mio está en casa limpiando mis zapatos.')
	frases.append('Google es mujer. No te deja terminar una frase y ya te está dando sugerencias.')
	frases.append('Si ves Godzilla al revés va de un lagarto gigante que reconstruye una ciudad destruida y después vuelve al océano haciendo el moonwalk.')
	frases.append('Vale... ¿Alguien sabe cómo sacarse tres clavos del pie? Absténgase quien opine que otro clavo es un buen método. Gracias.')
	frases.append('Una relación sin sexo es como un coche con el depósito vacío: por más que te guste, no va a ninguna parte.')
	frases.append('- ¿Qué tiene en esa botella?- Es solamente agua, Sr. Agente.- Oiga, ¡esto es vino!- ¡Alabado sea el Señor!')
	frases.append('Si buscas en Google "suicidio" lo primero que sale es el Teléfono de la Esperanza. Lo que se llama una contraoferta.')
	frases.append('No pegueis a un tio con gafas. Pegadle con un bate de beisbol que seguro que duele más.')
	frases.append('Nada define mejor lo que es la Iglesia como esas velas de mentira que se encienden echando una moneda.')
	frases.append('¿Has probado la comida africana? Ellos tampoco.')
	frases.append('Me encanta cagar. Yo si me dieran a elegir entre una mujer muy guapa y cagar elegiría a la mujer. Pero cagar también me gusta mucho.')
	frases.append('El "Call of Duty Modern Warfare 3" fue lanzado en Iran con el nombre de "Los Sims".')
	frases.append('Me compre un ebook y ahora la gente no puede ver lo intelectual que es mi lectura. First World Problems.')
	frases.append('La primera regla del club de la menopausia es que no hay reglas.')
	frases.append('-Oye, ¿a tu abuela le gusta la mecánica? - No, ¿por? - Pues entonces acaba de atropellarla un autobús.')
	frases.append('-Schrödinger, cariño mío, ¿está ya dentro? -Mmmm... sí y no...')
	frases.append('Ultima hora: Una joven ha sido asesinada en Lanzarote. Y esto es todo por hoy. Son las 21h y una menos en canarias.')
	frases.append('Soy tan catalán que me siento encima de mi mano antes e pagar para que parezca que me invitan.')
	frases.append('Ser pobre y de derechas es como ser puta y pagar el polvo.')
	frases.append('- Pues nada señor Rajoy, ahora tiene usted que gobernar. - Depende. Yo no he prometido nada.')
	frases.append('El ateísmo no tiene cura.')
	frases.append('-José, esto es una deshonra para mi familia, tengo que ocultar a nuestro hijo. -Calla María, que tengo una idea...')
	frases.append('Esta semana en "Cuarto Milenio" contaremos con el testimonio de una persona que asegura haber visto en Urgencias a un gitano esperando solo.')
	frases.append('Voy a tomar darme una ducha caliente. Es como una ducha normal, pero conmigo en ella.')
	frases.append('-¿Que haces tanto tiempo en el baño, hijo? -Ahorrar, mamá. -¿Cómo que ahorrar? -Una llamada de media hora y una cena.')
	frases.append('Queria vida. Cuando dije: "¿Puede esto ir a peor?" era una pregunta retorica, no un desafio.')
	frases.append('- ¿Estás más gordo?- Es por exigencias del guión. Estoy rodando una película en la que interpreto a tu puta madre.')
	frases.append('¿Aburrido? Simplemente envia un sms a un numero al azar que diga: "Estoy embarazada".')
	frases.append('No sé si VLC es el mejor reproductor de video, pero sí que es el que más invierte en publicidad. Hoy, 24 kms de anuncios en la autopista.')
	frases.append('Eres más rastrero que ganar por reliquias en el Age of Empires.')
	frases.append('Tio, yo quiero ser un estado, a ver si me llueven un par de milloncejos alemanes.')
	frases.append('A quien madruga, Dios le ayuda*. *Excepto si eres homosexual, ateo, o no marcas la X en la casilla de la Iglesia. RefraneroPPopular')
	frases.append('Si estás en una timba de Poker fumando chocolate y te sorprende la policía, lo normal es tirar la mano y esconder la piedra.')
	frases.append('-Estás gorda. +No, te equivocas, retengo líquidos. -Sí, y croquetas, estofado de ternera y huevos fritos con beicon.')
	frases.append('Todo lo que quiero para navidades eres tú. LoL, nope. xD. Era coña, quiero un movil nuevo.')
	frases.append('Déjate de tonterías. Trae más cerveza.')
	frases.append('La vida es como una caja de bombones. No le dura mucho a la gente gorda.')
	frases.append('Algunas personas son como los muelles. No sirven para mucho, pero te consiguen arrancar una sonrisa cuando les empujas escaleras abajo.')
	frases.append('¡Leed la biblia! Necesitamos mas ateos.')
	frases.append('Cuando dije que no puedes comprar mi amor me referia a que no sería posible con tu salario.')
	frases.append('Al metérsela a mi novia, me saltó un banner: "ENHORABUENA, ERES EL VISITANTE 1.000.000". Ella será algo puta, pero ese Audi me lo quedo yo.')
	frases.append('-¿Te acuestas con otros hombres?-Sí.-¡Lucía! ¿Me engañas?-No te engaño, no. Te lo juro, me los trinco de dos en dos.')
	frases.append('¿Cuál es la diferencia entre una prostituta muerta y un ferrari? Que no tengo un ferrari en mi garaje.')
	frases.append('Dios mio, dame modestia que del resto voy sobrado.')
	frases.append('- Doctor, mi pene está muy rojo. + ¿Con qué frecuencia se masturba? - 60 Hz.')
	frases.append('Dios quitó a Adán una sola costilla, porque si le quita las dos se llega a chupársela y ya me contaréis qué pinta Eva en todo esto.')
	frases.append('Todos los organismos tienden al mínimo consumo de energía, no me culpes por ser vago, la ciencia me avala.')
	frases.append('Lo bueno de follar con Penélope Cruz es que si finge los orgasmos te enteras, porque lo suyo no es la interpretación.')
	frases.append('En telecinco ocurren cosas para anormales.')
	frases.append('Del ratoncito pérez aprendí que puedo dar partes de mi cuerpo a cambio de dinero.')
	frases.append('Ese momento embarazoso en el que estás en un mcdonalds y ves a un emo pedir un happy meal.')
	frases.append('El PP desea a todos los españoles Navidad. Porque desear Feliz Navidad ya es un despilfarro.')
	frases.append('De todos los miembros de mi familia, con el que más disfruto es con el mío')
	frases.append('La infancia es como una gran borrachera. Todo el mundo se acuerda de lo que has hecho menos tú.')
	frases.append('Con mis 32, tengo el cuerpo de un chaval de 22 años. Está en el maletero de mi coche.')
	frases.append('Estoy más acojonado que cuando el Hombre de Hojalata descubrió que sus vecinos eran gitanos.')
	frases.append('Que Urdangarín presente las campanadas para que nos explique lo de los cuartos')
	frases.append('Ponerle de nombre a una clínica de abortos: "Qué embarazo ni qué niño muerto" en plan disimulado.')
	frases.append('Si la tradición de comer 12 uvas viene de un excedente de uva hace 100 años. ¿Por qué este año no comemos gente en paro?')
	frases.append('Con lo fácil que habría sido dejar el anillo en un campamento gitano. En dos minutos estaría fundido y vendido. ElSeñorDeLosAnillos')
	frases.append('No tengo un problema con la cafeina. Tengo un problema sin la cafeina.')
	frases.append('-¿Querrías ser para mi el sol de mi vida? -Awww, ¡Claro! -¡Pues mantente a 149.600.000 kilómetros de mi!')
	frases.append('¿Cuál es el desayuno favorito de Stevie Wonder? Sobaos pasiegos')
	frases.append('-Entonces ¿le interesa la oferta?-¿Qué oferta?-La de mi polla en su boca abierta. JAJAJAJA No, en serio, que si quiere los libros.')
	frases.append('Cuando Rajoy pronuncia la cuádruple S de Mississippi, se curva el espacio tiempo y ya es Renacimiento en El Corte Inglés.')
	frases.append('Madurar es darse cuenta de que la madre de Bambi está a 6.50€/kg')
	frases.append('-Me he comprado una cámara nueva.-¿Ah, sí? ¿Y qué objetivo tienes?-Los judíos.(Adolf Hitler, 1939)')
	frases.append('"El capitalismo es la raiz de todos los males" - posteado hace 5 minutos via iPad')
	frases.append('Te apuesto un embarazo no deseado a que en el fondo estas a favor de la libre elección.')
	frases.append('Queridos optimista y pesimista: Gracias. Mientras vosotros discutíais sobre el vaso de agua yo me lo bebí -Oportunista')
	frases.append('¿En que se diferencia un negro de una rueda? En que si a la rueda le pones cadenas no canta.')
	frases.append('John Lennon decia "all you need is love" pero un chaleco antibalas tampoco le habría venido mal')
	frases.append('-¿Ringo Starr? -No, Ringo salir. No decir donde. Yo suponer, él volver tarde')
	frases.append('-Toreo a crías de ciervo con las dos manos. ¿Qué soy?-Imbécil.-Iba a decir "bambidiestro" pero tu afirmación es irrefutable.')
	frases.append('El policía: - Señor ¿Sabía que su esposa se cayó del coche hace 10 Km.? - ¡Oh, gracias a Dios! Creí que me había quedado sordo.')
	frases.append('Me voy a dormir. Espero no soñar con pelis o series, que el FBI está al acecho.')
	frases.append('Si la vida fuera cerveza me la tomaria más en serio.')
	frases.append('-¿Qué hace aquí Rajoy? -Me pediste que lo trajera. -Te dije que trajeras la mayor empanada gallega qu... Vale, fallo mío por no especificar')
	frases.append('¿Tienes miedo de morir solo? ¡Hazte conductor de autobus!')
	frases.append('El Rey es como el Plsatidecor blanco, hay que pagarlo aunque no valga para nada.')
	frases.append('-¿Nos pillamos un ciego? -Ok, ¿qué le hacemos hoy? -Lo de darle una cuchilla y decirle que era una armónica estuvo guay.')
	frases.append('Acabo de dejar a mi novia. La verdad, no me importaba que tuviese los ojos azules de su madre, pero lo del pene de su padre era pasarse.')
	frases.append('¡Ultimas noticias! El dueño de Megaupload pide ser juzgado en Valencia. ')
	frases.append('The only "b" word you should call a girl is beautiful. Bitches love to be called beautiful.')
	frases.append('¡Ronda de preguntas! Pregúntame sobre mi trastorno de déficit de atención o empanada o gato. Un perro. Tengo una bici. ¿Te gusta la tele?')
	frases.append('Cerrar Megaupload para subir la venta de contenidos multimedia es como cerrar Mcdonalds para subir la venta de verduras')
	frases.append('Da un pez a un hombre y le alimentaras un dia. No le enseñes a pescar, y alimentate tú. Ya es mayorcito y pescar no es complicado.')
	frases.append('Soy bueno, pero a estas alturas ya no me atrevería a competir al Angry Birds contra ningún diputado.')
	frases.append('Iba en moto y he visto a Fernando Torres. Le he dicho: sube que te llevo de paquete ¡cómo se ha puesto! Ha querido darme una patada. Falló.')
	frases.append('Cuando muera espero no estar haciendo nada, asi la gente podrá decir que morí haciendo lo que más me gustaba')
	frases.append('Mis amigos se sacaron el carné de conducir a la primera Yo lo intenté, pero cuando el motor empezó a echar humo tuve que cambiar a segunda')
	frases.append('Mi nivel de fisica es lo suficientemente bueno como para arruinar peliculas de SciFi pero no como para sacarme la carrera. FirstWorldProblems')
	frases.append('Lo más difícil de cocinar vegetales es hacer que la silla de ruedas quepa en el horno.')
	frases.append('-Chúpamela! -No -Que me la chupes! -Que no! -Ya bostezarás, ya...')
	frases.append('Eché una partida de ajedrez con mi sobrino de 8 años, obviamente, le di una paliza bestial. Pero me ganó el muy hijo de puta.')
	frases.append('-De todos los superhéroes, ¿Cuál es el poder que querrías tener? -El poder adquisitivo de Batman.')
	frases.append('-¿De qué te ríes? -Han atropelladoa un niño ahi abajo -No es divertido -Hombre, esque así contado pierde la gracia.')
	frases.append('¡Resaca y gana!')
	frases.append('De los creadores de: "Estoy perfecto para conducir" y los guionistas de: "Hablo ingés medio" llega: NO ME LA FOLLO PORQUE NO QUIERO.')
	frases.append('¿Qué tiene 20 cm y no va a ser chupada este San Valentín? La pipa de crack de Whitney Houston.')
	frases.append('Con la tontería de "El que la sigue, la consigue", llevo ya tres órdenes de alejamiento y dos denuncias por acoso.')
	frases.append('¿Cómo llama Pitbull a Voldemort? Quien-ya-tu-sabeh')
	frases.append('Cuando tengo las manos heladas escribo realmente bien en finlandés.')
	frases.append('-¡¿QUé QUEREMOS?! -¡Conversaciones coherentes! -¡¿HELICóPTERO FOSFORITO?! -¡Yo tampoco soy un bolso!')
	frases.append('El gran problema de las mujeres con los hombres, es que relacionan "madurez" con "no pensar en sexo cada vez que me ves"')
	frases.append('Gente que dice que "le gusta" SAW y luego no se dejarían ni cortar un dedo de nada')
	frases.append('Ahora es cuando contraatacamos a Siberia y le mandamos una ola de parados.')
	frases.append('La puta de tu ex novia me ve y ni me saluda. - Hemos vuelto. - Vaya tela lo de Contador, ¿eh?')
	frases.append('Y me dice "¿Y tú de qué vas?". Total, que le solté una hostia. Luego me estní culpable porque era Carnaval.')
	frases.append('-Cariño, dime algo profundo. +Ombligo de Falete.')
	frases.append('Yo quería dedicarme al reggaeton, pero me saqué la ESO... demasiado tarde.')
	frases.append('¿Qué sale si cruzas un negro con un pulpo?Ni puta idea, pero tiene que robar que da gusto.')
	frases.append('Lo de Grecia tenemos que hacerlo en España Ya!! Esos yogures estan cojonudos!!')
	frases.append('¿Me hago una paja o no? La erección está en mis manos.')
	frases.append('El PP es ese amigo que te dice: "quita quita, que tú no sabes" y al final lo acaba jodiendo más.')
	frases.append('Hay quien madruga, y luego están a los que Dios ayuda. No me mezcles temas porque no.')
	frases.append('Colarse en las salas postparto de los hospitales donde están los bebés y cambiar las identificaciones. Si hay negros por medio mejor.')
	frases.append('Urdangarín declara que su programa favorito es Atrapa un millón.')
	frases.append('-¿Tú bebes agua? -Sí -Demasiadas coincidencias. Follemos.')
	frases.append('Yo iba para futbolista, pero no me sale lo de escupir mocos por la nariz.')
	frases.append('Me gusta acercarme a una treintañera y decirle: Señora, ¿tiene hora?. Y parece que no, pero le he jodido el día.')
	frases.append('Si el roce hace el cariño estos zapatos nuevos me quieren follar.')
	frases.append('Siguen empeñados en cuestionar la legitimidad de Putin. Fue votado por un 112% de los rusos, qué más quieren.')
	frases.append('Cuántos ingenieros de Apple hacen falta para cambiar una bombilla? Ninguno, llaman a Marketing para que digan que la oscuridad es cool.')
	frases.append('Subir al metro, comenzar a toser, simular arcadas, escupir, sacar una grabadora y decir: Día 23, el virus ha mutado, he de encontrar la cura')
	frases.append('-Mi novia pincha. -¿Es DJ? - No, portuguesa')
	frases.append('¿CóMO SE PUEDE RECUPERAR LA TECLA DE BLOQUEAR MAYúSCULAS QUE SE TE HA INTRODUCIDO EN EL ANO? ACCIDENTALMENTE, CLARO. ES PARA UN AMIGO.')
	frases.append('-Hola le llamo del 1004, ¿con quién hablo? -Soy Fernando Torres. -Ok, ¿puede pasarme con el titular?')
	frases.append('¡Es mi señora y me la follo cuando quiere!')
	frases.append('A veces sueño que estoy conduciendo hacia atrás. Luego me despierto y estoy conduciendo normal.')
	frases.append('-Yo tomaré rape y mi señora carne +¿La pasamos por la piedra? -Dirá que le duele la cabeza, insistid.')
	frases.append('Llegué al cuarto de mi hijo y tenía todas las piezas de lego tiradas. Así que le monté un pollo que flipas. Lo más difícil fue el pico.')
	frases.append('¿Dónde encuentras un niño sin extremidades? Donde lo dejaste.')
	frases.append('Mostrarle un tampón usado a un arqueólogo y preguntarle de qué periodo es.')
	frases.append('Mi futuro parece tan negro que si lo ve Angelina Jolie lo adopta.')
	frases.append('Las prostitutas soviéticas son como la A-6 primero Las Rozas y luego Las Matas')
	frases.append('- Tomad y comed, porque esta es mi carne... - ¡Joder Jesucristo, guárdate la chorra dentro de la túnica, anda!')
	frases.append('Que los sindicatos convoquen huelga es como si yo te veo morir desangrado sin hacer nada y luego organizo tu funeral.')
	frases.append('Dale porno a un hombre, se masturbará diez minutos. Enséñale a un hombre a buscar porno, y se masturbará por siempre.')
	frases.append('El chiste más corto del mundo: Esto son dos mujeres juntas calladas.')
	frases.append('-Creo que está tronando. -Imposible. Son las 3AM. -¿Y qué? -Pues que son horas intempestivas. -A dormir al sofá. -Sí cari.')
	frases.append('Batman, estamos sufriendo un atraco en la calle Goya, es de día, está soleado y la Bat-señal no funciona. Si lo lees ven cagando ostias.')
	frases.append('Si amas a alguien, drógalo con cloroformo y átalo en tu cama. Si se queda, es tuyo, si logra huir, dispárale antes de que te denuncie.')
	frases.append('Lo más jodido de trabajar en equipo es convencer al resto de que no tienen ni puta idea.')
	frases.append('Me gusta la esquizofrenia, pero tampoco es que me vuelva loco.')
	frases.append('- ¿De que murió Paco? - ¿Sabes cual es ese cartel que dice "no cruzar por las vías del tren"? - Sí. - Pues le dieron 8 puñaladas enfrente.')
	frases.append('- Pues yo a tu ex-novia me la follaba.- Está buena. ¿Eh? - ... creo que no me has entendido.')
	frases.append('Quiero ser hardcore pero mi mama no me deja. #First World Problems')
	frases.append('Si el vino tinto es la sangre de Dios... ¿Qué es el vino blanco?')
	frases.append('+¿Por qué vas dando palmas por la calle? -Para espantar a los elefantes. +Pero si no hay. -Coño, porque funciona.')
	frases.append('He fallado tanto jugando al Big Brain Academy de la Wii, que cuando he terminado me ha impreso un certificado de minusvalía.')
	frases.append('-¡Tengo una salud de hierro! JAJAJA. -Ya veo. -¡Y los nervios de acero! JAJAJA. -Para. -¡Y mucha chispa! JAJAJA, -Ya no tiene gracia, Robocop.')
	frases.append('En España se vive muy bien, salvo que seas autónomo, obrero, parado, gay, estudiante, enfermo, clase media, pensionista, ateo o educado.')
	frases.append('Si no te gusta como conduzco, apártate de la acera y deja de chillar.')
	frases.append('Si bebes alcohol eres alcohólico, si bebes fanta eres el que conduce. Ni fantástico ni ostias.')
	frases.append('Querida dieta. Las cosas no están yendo bien entre nosotros. No soy yo, eres tú. Eres sosa, aburrida y no puedo dejar de ponerte los cuernos')
	frases.append('No, a ver, en serio... necesito saberlo. De todos los utensilios aptos para comer arroz... ¿cómo demonios pudieron ganar dos putos palillos?')
	frases.append('La casa real es como Internet Explorer. A casi nadie le gusta y saben que hay opciones mejores, pero como vienen con el propio sistema...')
	frases.append('+¿Mamá, puedo salir? -No! +¿Cómo se llama eso que usas para dar sabor a la comida? -Semen +Si insistQUEEEEEE?!')
	frases.append('-Su majestad, le voy a recetar estos somníferos paquiduerma mejor. -YA VALE LA BROMITA, NO? -Su majestad, por favor, no me elefante la voz.')
	frases.append('Ultima hora: Joven expulsada de Tuenti después de escribir una frase sin ningún error ortográfico.')
	frases.append('-Disculpe, me puede freír este pescado, está crudo. -Señor, este restaurante es Japonés. -Peldón, me puede fleil este pescado, esta cludo.')
	frases.append('No pienses en ti como una persona fea. Piensa en ti como en un mono precioso.')
	frases.append('-Ayer me comí un coñazo de película. +¿Cual era? Para no descargarla. -No me has entendido...')
	frases.append('En una discoteca, junto a los altavoces, ya pueden decirte que se han follado y matado a tu madre, que tú asientes con la cabeza y sonríes.')
	frases.append('Mi plan es viajar en el tiempo y matar a Hitler siendo un bebé. No esperará que un bebé lo ataque. Cuento con el factor sorpresa.')
	frases.append('A mi las mujeres guapas que solo destacan por su físico no me dicen nada. De hecho, no me dirigen la palabra.')
	frases.append('Dices que sólo te quiero por el sexo... Pero es mi corazón el que bombea toda esa sangre hasta mi pene por ti. ')
	frases.append('Mi novia, cuando viene a casa, no quiere dormir en la cama grande porque mi abuela murió en ella. Al final tendré que ahorrar y enterrarla.')
	frases.append('- Oye, ¿tú ya has probado a darle por el otro agujero? - Si hombre, y que se quede preñada. No, deja, deja.')
	count = 0
	for frase in frases:
		cur.execute("INSERT INTO Frases VALUES("+str(count)+",'"+str(frase)+"')")
		count += 1
	con.commit()

	
	print ("funciona")
except:
	print ("Error")
	sys.exit(1)
    
finally:
    
    if con:
        con.close()